export { default as cskh } from './cskh.svg'
export { default as thongbao } from './thongbao.svg'
export { default as timkiem } from './timkiem.svg'
export { default as yeuthich } from './yeuthich.svg'
export { default as chiase } from './chiase.svg'
export { default as diachi } from './diachi.svg'
