export { default as cskh } from './cskh.svg'
export { default as thongbao } from './thongbao.svg'
export { default as timkiem } from './timkiem.svg'

export { default as chuyenkhoa } from '../../DatKham/icon/Specialist.svg'
export { default as bacsi } from '../../DatKham/icon/Doctor.svg'
export { default as dichvu } from '../../DatKham/icon/Service.svg'
export { default as lichkham } from '../../DatKham/icon/Calender.svg'
export { default as thongtin } from '../../DatKham/icon/thongtin.svg'

//Specialist
export { default as ChamSocGiamNhe } from '../../DatKham/ListDatKham/Specialist/icons/ChamSocGiamNhe.svg'
export { default as ChanThuongChinhHinh } from '../../DatKham/ListDatKham/Specialist/icons/ChanThuongChinhHinh.svg'
export { default as DaLieu } from '../../DatKham/ListDatKham/Specialist/icons/DaLieu.svg'
export { default as HauMon } from '../../DatKham/ListDatKham/Specialist/icons/HauMon.svg'
export { default as Mat } from '../../DatKham/ListDatKham/Specialist/icons/Mat.svg'
export { default as Nhi } from '../../DatKham/ListDatKham/Specialist/icons/Nhi.svg'
export { default as NoiTiet } from '../../DatKham/ListDatKham/Specialist/icons/NoiTiet.svg'
export { default as Phoi } from '../../DatKham/ListDatKham/Specialist/icons/Phoi.svg'
export { default as RangHamMat } from '../../DatKham/ListDatKham/Specialist/icons/RangHamMat.svg'
export { default as TaiMuiHong } from '../../DatKham/ListDatKham/Specialist/icons/TaiMuiHong.svg'
export { default as ThanKinh } from '../../DatKham/ListDatKham/Specialist/icons/ThanKinh.svg'
export { default as TieuHoa } from '../../DatKham/ListDatKham/Specialist/icons/TieuHoa.svg'
export { default as TimMach } from '../../DatKham/ListDatKham/Specialist/icons/TimMach.svg'
export { default as TuVanDinhDuong } from '../../DatKham/ListDatKham/Specialist/icons/TuVanDinhDuong.svg'
export { default as XuongKhop } from '../../DatKham/ListDatKham/Specialist/icons/XuongKhop.svg'

//Doctor
export { default as Man } from '../../DatKham/ListDatKham/Doctor/icons/DoctorMan.svg'
export { default as Woman } from '../../DatKham/ListDatKham/Doctor/icons/DoctorWoman.svg'
