export { default as cskh } from './cskh.svg'
export { default as thongbao } from './thongbao.svg'
export { default as timkiem } from './timkiem.svg'
export { default as yeuthich } from './yeuthich.svg'

export { default as chuyenkhoa } from '@componentsTest/DatKham/icon/Specialist.svg'
export { default as bacsi } from '@componentsTest/DatKham/icon/Doctor.svg'
export { default as dichvu } from '@componentsTest/DatKham/icon/Service.svg'
export { default as lichkham } from '@componentsTest/DatKham/icon/Calender.svg'
export { default as thongtin } from '@componentsTest/DatKham/icon/thongtin.svg'
