FROM node:12 as builder
WORKDIR /app
COPY . /app
RUN yarn install --save --network-timeout 100000
RUN yarn run build:testing

FROM node:12.16.2-alpine3.11

WORKDIR /app
RUN yarn global add serve
COPY --from=builder /app .
EXPOSE 3000
CMD ["serve","-p","3000","-c","1","-s","build"]
