FROM node:12 as builder1
WORKDIR /app
COPY . /app
RUN yarn install --save --network-timeout 100000
RUN yarn run build

FROM node:12.16.2-alpine3.11

WORKDIR /app
COPY --from=builder1 /app .
EXPOSE 3000
CMD ["yarn" ,"start"]
