export namespace HosptailTypes {
  export enum Information {
    INFORMATION_REQUEST = 'INFORMATION_REQUEST',
    INFORMATION_REQUEST_SUCCESS = 'INFORMATION_REQUEST_SUCCESS',
    INFORMATION_CLEAR = 'INFORMATION_CLEAR'
  }

  export enum Feature {
    FEATURE_BY_PARTNER_REQUEST = 'FEATURE_BY_PARTNER_REQUEST',
    FEATURE_BY_PARTNER_REQUEST_SUCCESS = 'FEATURE_BY_PARTNER_REQUEST_SUCCESS'
  }

  export enum ListHospital {
    LIST_HOSPITAL_REQUEST = 'LIST_HOSPITAL_REQUEST',
    LIST_HOSPITAL_REQUEST_SUCCESS = 'LIST_HOSPITAL_REQUEST_SUCCESS'
  }
  export enum BookingTree {
    BOOKING_TREE_REQUEST = 'BOOKING_TREE_REQUEST',
    BOOKING_TREE_REQUEST_SUCCESS = 'BOOKING_TREE_REQUEST_SUCCESS'
  }
}
