export const API_CMS: string = 'https://cms.medpro.com.vn'
export const API_BE: string = 'https://medpro-api-v2-testing.medpro.com.vn'
export const API_Image: string = 'https://resource-testing.medpro.com.vn'
export const login: string = 'https://id-v121.medpro.com.vn/check-phone'
export const BO_API: string = 'https://bo-api-testing.medpro.com.vn'
