export const API_CMS = 'https://cms.medpro.com.vn'
export const API_BE = 'https://medpro-api-v3-testing.medpro.com.vn'
export const API_Image = 'https://resource-testing.medpro.com.vn'
export const login = 'https://id-testing.medpro.com.vn/check-phone'
export const BO_API = 'https://bo-api-testing.medpro.com.vn'
