// Kiểm soát hành động -----------------------------------------------------------------------------------------

export namespace NewsTypes {
  export enum NewsAndEvent {
    NEWS_AND_EVENT_REQUEST = 'NEWS_AND_EVENT_REQUEST',
    NEWS_AND_EVENT_REQUEST_SUCCESS = 'NEWS_AND_EVENT_REQUEST_SUCCESS',
    NEWS_AND_EVENT_REQUEST_FAILS = 'NEWS_AND_EVENT_REQUEST_FAILS'
  }
  export enum ListNewsBanner {
    LIST_NEWS_BANNER_REQUEST = 'LIST_NEWS_BANNER_REQUEST',
    LIST_NEWS_BANNER_REQUEST_SUCCESS = 'LIST_NEWS_BANNER_REQUEST_SUCCESS',
    LIST_NEWS_BANNER_REQUEST_FAILS = 'LIST_NEWS_BANNER_REQUEST_FAILS'
  }
  export enum ListNewsContent {
    LIST_NEWS_CONTENT_REQUEST = 'LIST_NEWS_CONTENT_REQUEST',
    LIST_NEWS_CONTENT_REQUEST_SUCCESS = 'LIST_NEWS_CONTENT_REQUEST_SUCCESS',
    LIST_NEWS_CONTENT_REQUEST_FAILS = 'LIST_NEWS_CONTENT_REQUEST_FAILS'
  }
  export enum CountNewsContent {
    COUNT_NEWS_CONTENT_REQUEST = 'COUNT_NEWS_CONTENT_REQUEST',
    COUNT_NEWS_CONTENT_REQUEST_SUCCESS = 'COUNT_NEWS_CONTENT_REQUEST_SUCCESS',
    COUNT_NEWS_CONTENT_REQUEST_FAILS = 'COUNT_NEWS_CONTENT_REQUEST_FAILS'
  }
  export enum DetailNews {
    DETAIL_NEWS_REQUEST = 'DETAIL_NEWS_REQUEST',
    DETAIL_NEWS_REQUEST_SUCCESS = 'DETAIL_NEWS_REQUEST_SUCCESS',
    DETAIL_NEWS_REQUEST_FAILS = 'DETAIL_NEWS_REQUEST_FAILS'
  }
}
