export namespace HosptailTypes {
  export enum Information {
    INFORMATION_REQUEST = 'INFORMATION_REQUEST',
    INFORMATION_REQUEST_SUCCESS = 'INFORMATION_REQUEST_SUCCESS',
    HOSPITAL_CLEAR_DETAILS = 'HOSPITAL_CLEAR_DETAILS'
  }

  export enum Feature {
    FEATURE_BY_PARTNER_REQUEST = 'FEATURE_BY_PARTNER_REQUEST',
    FEATURE_BY_PARTNER_REQUEST_SUCCESS = 'FEATURE_BY_PARTNER_REQUEST_SUCCESS'
  }

  export enum ListHospital {
    LIST_HOSPITAL_REQUEST = 'LIST_HOSPITAL_REQUEST',
    LIST_HOSPITAL_REQUEST_SUCCESS = 'LIST_HOSPITAL_REQUEST_SUCCESS'
  }
}
